
APPSFLYER_COL_INDEX = 'C:F'
APPSFLYER_COL_DATE = 'date'
APPSFLYER_COL_COUNTRY = 'country'
APPSFLYER_COL_INSTALL = 'install_af'
APPSFLYER_COL_DAY1_ACTION = 'day_1'
APPSFLYER_COL_DAY1_RETENTION = 'retention'

FACEBOOK_COL_INDEX = 'B,D,E,F'
FACEBOOK_COL_DATE = 'date'
FACEBOOK_COL_COUNTRY = 'country'
FACEBOOK_COL_INSTALL = 'install_fb'
FACEBOOK_COL_SPEND = 'spend'

MERGE_COL_PROFIT = 'profit'
MERGER_COL_FULL_PAYMENT = 'full_payment'
MERGER_COL_ACTUAL_PAYMENT = 'actual_payment'

CONFIG_RETENTION_INFO = 'retention_info'
CONFIG_START_DATE = 'start_date'
CONFIG_END_DATE = 'end_date'
CONFIG_KPI = 'kpi'
CONFIG_COUNTRY = 'country'
CONFIG_PRICE_THRESHOLD = 'priceThreshold'
CONFIG_PRICE = 'price'
CONFIG_THRESHOLD = 'threshold'
CONFIG_COEFFICIENT = 'coefficient'
CONFIG_CAL_PLATFORM = 'calculate_platform'
CONFIG_CHECK_TYPE = 'check_type'

CAL_PLATFORM_FB = 'facebook'
CAL_PLATFORM_AF = 'appsflyer'

CHECK_TYPE_NORMAL = 'normal'
CHECK_TYPE_EQUAL = 'equal_ratio'

EQUAL_RATIO_FLAG = -1
